# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

In [2]:
# Import pandas
import pandas as pd

In [3]:
# Create a series of three different colours
colors = pd.Series(["Blue", "Pink", "Red"])

In [4]:
# View the series of different colours
colors

0    Blue
1    Pink
2     Red
dtype: object

In [5]:
# Create a series of three different car types and view it
cars = pd.Series(["Tata", "Mahindra", "Thar"])
cars

0        Tata
1    Mahindra
2        Thar
dtype: object

In [10]:
# Combine the Series of cars and colours into a DataFrame
combine_data = pd.DataFrame({"Car make": cars, "Colour": colors})
combine_data

   Car make Colour
0      Tata   Blue
1  Mahindra   Pink
2      Thar    Red

In [11]:
# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/refs/heads/master/data/car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [12]:
# Export the DataFrame you created to a .csv file
car_sales.to_csv("exported-car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [13]:
# Find the different datatypes of the car data DataFrame
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [14]:
# Describe your current car sales DataFrame using describe()
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [15]:
# Get information about your DataFrame using info()
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

What does it show you?

In [16]:
# Create a Series of different numbers and find the mean of them
series = pd.Series([7643, 5434, 9898])
series.mean()

np.float64(7658.333333333333)

In [17]:
# Create a Series of different numbers and find the sum of them
series = pd.Series([7643, 5434, 9898])
series.sum()

np.int64(22975)

In [18]:
# List out all the column names of the car sales DataFrame
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [19]:
# Find the length of the car sales DataFrame
car_sales.shape

(10, 5)

In [20]:
# Show the first 5 rows of the car sales DataFrame
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [21]:
# Show the first 7 rows of the car sales DataFrame
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [22]:
# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [23]:
# Use .loc to select the row at index 3 of the car sales DataFrame
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [24]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

Notice how they're the same? Why do you think this is?

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [25]:
# Select the "Odometer (KM)" column from the car sales DataFrame
car_sales["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [26]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame
car_sales["Odometer (KM)"].mean()

np.float64(78601.4)

In [30]:
# Select the rows with over 100,000 kilometers on the Odometer
car_sales[car_sales["Odometer (KM)"] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00

In [ ]:
# Create a crosstab of the Make and Doors columns

In [ ]:
# Group columns of the car sales DataFrame by the Make column and find the average

In [ ]:
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline

In [ ]:
# Create a histogram of the Odometer column using hist()

In [ ]:
# Try to plot the Price column using plot()

Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [ ]:
# Remove the punctuation from price column

In [ ]:
# Check the changes to the price column

In [ ]:
# Remove the two extra zeros at the end of the price column

In [ ]:
# Check the changes to the Price column

In [ ]:
# Change the datatype of the Price column to integers

In [ ]:
# Lower the strings of the Make column

If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [ ]:
# Make lowering the case of the Make column permanent

In [ ]:
# Check the car sales DataFrame

Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [ ]:
# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")


# Check out the new DataFrame

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [ ]:
# Fill the Odometer column missing values with the mean of the column inplace

In [ ]:
# View the car sales missing DataFrame and verify the changes

In [ ]:
# Remove the rest of the missing data inplace

In [ ]:
# Verify the missing values are removed by viewing the DataFrame

We'll now start to add columns to our DataFrame.

In [ ]:
# Create a "Seats" column where every row has a value of 5

In [ ]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame

In [ ]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame

In [ ]:
# Remove the last column you added using .drop()

In [ ]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable

Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [ ]:
# Reset the indexes of the shuffled DataFrame

Notice the index numbers have been changed to have order (start from 0).

In [ ]:
# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame

In [ ]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers

## Extensions

For more exercises, check out the pandas documentation, particularly the [10-minutes to pandas section](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

One great exercise would be to retype out the entire section into a Jupyter Notebook of your own.

Get hands-on with the code and see what it does.

The next place you should check out are the [top questions and answers on Stack Overflow for pandas](https://stackoverflow.com/questions/tagged/pandas?sort=MostVotes&edited=true). Often, these contain some of the most useful and common pandas functions. Be sure to play around with the different filters!

Finally, always remember, the best way to learn something new to is try it. Make mistakes. Ask questions, get things wrong, take note of the things you do most often. And don't worry if you keep making the same mistake, pandas has many ways to do the same thing and is a big library. So it'll likely take a while before you get the hang of it.